# Generated by Django 5.2 on 2025-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('image', models.ImageField(upload_to='movies')),
            ],
        ),
    ]
